name: mockify
description: Mockify is a Dart class used for mocking function calls and verifying method invocations.
version: 1.0.0

environment:
  sdk: ^3.3.1
dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
